### ISSUE TITLE
bsdate error "Unexpected next character"

### ISSUE THREAD

**Issue by jakobgoldstein** [vitalets/angular-xeditable#326]
Using the date picker as explained in the demo leads to an error:

Html:
```
<a href="#" editable-bsdate="vm.user.dob"
                  e-datepicker-popup="dd-MMMM-yyyy">
                  {{ (vm.user.dob | date:"dd/MM/yyyy") || 'empty' }}
               </a>
```

Controller: 

```
vm.user = {
            dob: new Date(1984, 4, 15)
         };
```

Mitteleuropäische Sommerzeit means CET Summertime...

```
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 46-46 [ä] in expression [Wed Jun 17 2015 14:47:31 GMT+0200 (Mitteleuropäische Sommerzeit)].
http://errors.angularjs.org/1.3.15/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%2046-46%20%5B%C3%A4%5D&p2=Wed%20Jun%2017%202015%2014%3A47%3A31%20GMT%2B0200%20(Mitteleurop%C3%A4ische%20Sommerzeit)
    at REGEX_STRING_REGEXP (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:63:12)
    at Lexer.throwError (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:11898:11)
    at Lexer.lex (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:11857:16)
    at Parser.parse (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:12018:30)
    at $parse (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:12737:39)
    at http://localhost:8000/probandenmgmt/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:1536:30
    at Object.forEach (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:323:20)
    at link (http://localhost:8000/probandenmgmt/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:1534:15)
    at http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:8252:44
    at invokeLinkFn (http://localhost:8000/probandenmgmt/bower_components/angular/angular.js:8258:9)
```

**Comment by bodhisatwag** [comment]
I have successfully got rid of this error by adding e-init-date="false". But not sure if its the proper way to do it.

**Comment by heston** [comment]
I just encountered this myself. Definitely a real issue, but the fix from @bodhisatwag seems to work.

**Comment by ncubo** [comment]
I tried that and now I don't have the error, but the datepicker popup doesn't appear :/

**Comment by ckosloski** [comment]
Is this still an issue with the latest release?
