### ISSUE TITLE
Table row not hiding when we hit Save button

### ISSUE THREAD

**Issue by exp-anoop** [vitalets/angular-xeditable#360]
Table row not hiding when we hit Save button on edit mode, showing the following error in the console .

angular.js:9959 TypeError: k.assign is not a function
    at c.m.save (http://localhost:8289/vendor/xeditable/xeditable.min.js:6:7840)
    at http://localhost:8289/vendor/xeditable/xeditable.min.js:6:12184
    at Array.forEach (native)
    at Object.forEach (http://localhost:8289/vendor/angular/angular.js:325:11)
    at FormController.g.$save (http://localhost:8289/vendor/xeditable/xeditable.min.js:6:12146)
    at val (http://localhost:8289/vendor/angular/angular.js:1054:18)
    at c (http://localhost:8289/vendor/xeditable/xeditable.min.js:6:14324)
    at Object.then (http://localhost:8289/vendor/xeditable/xeditable.min.js:6:14596)
    at FormController.a (http://localhost:8289/vendor/xeditable/xeditable.min.js:6:11635)
    at http://localhost:8289/vendor/angular/angular.js:1049:18

Please help me to resolve this issue.

**Comment by mylonos** [comment]
Have similar issue, 

TypeError: k.assign is not a function
    at c.m.save (xeditable.min.js:170)
    at xeditable.min.js:298
    at Object.forEach (angular.js:332)
    at FormController.g.$save (xeditable.min.js:297)
    at val (angular.js:1029)
    at c (xeditable.min.js:357)
    at Object.then (xeditable.min.js:368)
    at FormController.a (xeditable.min.js:275)
    at angular.js:1024
    at c (xeditable.min.js:357)

**Comment by ckosloski** [comment]
Can you provide a Plunker or JSFiddle showing your issue?

**Comment by ckosloski** [comment]
@exp-anoop are you still having an issue?

**Comment by exp-anoop** [comment]
I think I solved this issue

**Comment by ckosloski** [comment]
OK, can you please close then?

**Comment by exp-anoop** [comment]
Sure

**Comment by rajesh-rns** [comment]
@exp-anoop  could you please provide info on how you fixed it? I am facing the exact same issue. Thanks
