### ISSUE TITLE
Datepicker options not being parsed

### ISSUE THREAD

**Issue by edmedo** [vitalets/angular-xeditable#490]
As per the title; when using `editable-bsdate`, options set in the scope and referenced in the `e-datepicker-options` attribute are being ignored. [Here's a JSFiddle](https://jsfiddle.net/edgiles/ydedrbxL/) example of the problem.

I imagine it's something to do with the datepicker essentially being nested and not knowing about the defaults on init, but I'm not sure. Am I being dense?

Thanks

**Comment by ckosloski** [comment]
Currently setting the datepicker-options is not supported.  You have to specify each property individually.
`e-showWeeks="false"`
`e-startingDay="1"`
`e-minDate="today"`

**Comment by edmedo** [comment]
Thanks @ckosloski, I did attempt that method but it also doesn't seem to work:
[https://jsfiddle.net/edgiles/7ap9xxce/1/](https://jsfiddle.net/edgiles/7ap9xxce/1/)

**Comment by ckosloski** [comment]
That is because the latest build doesn't have my changes I did to fix this issue (adding showWeeks, min/max day support).
@eugef Can you do a build please?

**Comment by edmedo** [comment]
Ah, ok good stuff, I will await the new build then. Thanks for your help.

**Comment by codeshri** [comment]
I am getting the following error when trying to use datepicker inside form/table.  Also when i set e-ng-required= inside <span/> element it doesn't apply required to  datepicker input element i applies that to a div. When will the be the new build with fixes available to download?   Hopefully that will fix error that i am getting.      Error Message:  angular.js:13642 Error: [$compile:ctreq] http://errors.angularjs.org/1.5.6/$compile/ctreq?p0=ngModel&p1=uibDatepicker
    at Error (native)
    at http://localhost:53928/bower_components/angular/angular.min.js:6:412
    at ib (http://localhost:53928/bower_components/angular/angular.min.js:71:437)
    at ib (http://localhost:53928/bower_components/angular/angular.min.js:72:1)
    at n (http://localhost:53928/bower_components/angular/angular.min.js:66:215)
    at http://localhost:53928/bower_components/angular/angular.min.js:77:99
    at g (http://localhost:53928/bower_components/angular/angular.min.js:58:429)
    at http://localhost:53928/bower_components/angular/angular.min.js:58:67
    at http://localhost:53928/bower_components/angular/angular.min.js:62:430
    at d (http://localhost:53928/bower_components/angular/angular.min.js:59:422) <li ng-transclude="">(anonymous function) @ angular.js:13642(anonymous function) @ angular.js:10287ia @ angular.js:9759n @ angular.js:9156g @ angular.js:8459n @ angular.js:9151g @ angular.js:8459(anonymous function) @ angular.js:8339(anonymous function) @ angular.js:8677d @ angular.js:8476l @ angular.js:9206(anonymous function) @ angular.js:25687$digest @ angular.js:17220$apply @ angular.js:17486(anonymous function) @ angular.js:25177Rf @ angular.js:3487d @ angular.js:3475
angular.js:13642 TypeError: Cannot read property 'getFullYear' of undefined
    at _refreshView (http://localhost:53928/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:26023)
    at refreshView (http://localhost:53928/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:22963)
    at init (http://localhost:53928/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:25824)
    at Object.link (http://localhost:53928/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js:7:29943)
    at http://localhost:53928/bower_components/angular/angular.min.js:16:230
    at ia (http://localhost:53928/bower_components/angular/angular.min.js:81:35)
    at n (http://localhost:53928/bower_components/angular/angular.min.js:66:176)
    at http://localhost:53928/bower_components/angular/angular.min.js:77:99
    at g (http://localhost:53928/bower_components/angular/angular.min.js:58:429)
    at http://localhost:53928/bower_components/angular/angular.min.js:58:67 <table class="uib-daypicker" role="grid" aria-labelledby="{{::uniqueId}}-title" aria-activedescendant="{{activeDateId}}" ng-switch-when="day" tabindex="0">

**Comment by edmedo** [comment]
Hi @eugef – sorry to ask but; how is it looking for a release today?

**Comment by eugef** [comment]
@edmedo, will try my best

**Comment by edmedo** [comment]
Hi @ckosloski - did those changes get merged? Using the current master branch, now `e-show-weeks` and `e-starting-day` work fine, but `e-min-date` doesn't work. (I've also tried `e-minDate`, as you suggested above)

**Comment by ckosloski** [comment]
My changes are merged, there just hasn't been a new build yet.  You could always download the src and build the latest for yourself.

**Comment by eugef** [comment]
Release 0.2.0 was just published

**Comment by codeshri** [comment]
Thank You!
